apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
  labels:
    app: k8s-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
      - name: k8s-test-app
        image: k8s-test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"

# Creates 3 replicas of the application
# Uses the locally built Docker image (k8s-test-app:latest)
# imagePullPolicy: Never tells Kubernetes to only use local images
# Sets resource limits and requests for each container
# Exposes port 3000
# Uses labels to identify the application