apiVersion: v1
kind: Service
metadata:
  name: k8s-test-app
spec:
  type: NodePort
  selector:
    app: k8s-test-app
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP

# Creates a NodePort service to expose the application
# Selects pods with label app: k8s-test-app
# Maps the service port 3000 to the container port 3000
# Type NodePort allows external access to the service