---
name: EKS Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 3-eks-deployment/app/**
      - 3-eks-deployment/terraform/**
      - 3-eks-deployment/k8s/**

env:
  TF_VAR_aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws-region: ${{ secrets.AWS_REGION }}
  TF_VAR_project_name: 'eks-app'
  TF_VAR_environment: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: 3-eks-deployment/app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

