---
name: EKS Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 3-eks-deployment/app/**
      - 3-eks-deployment/terraform/**
      - 3-eks-deployment/k8s/**

env:
  TF_VAR_aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws-region: ${{ secrets.AWS_REGION }}
  TF_VAR_project_name: 'eks-app'
  TF_VAR_environment: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: 3-eks-deployment/app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform -chdir=3-eks-deployment/terraform init

      - name: Select Terraform Workspace
        run: terraform -chdir=3-eks-deployment/terraform workspace select dev || terraform -chdir=3-eks-deployment/terraform workspace new dev

      - name: Terraform Validate
        run: terraform -chdir=3-eks-deployment/terraform validate

      - name: Terraform Plan
        run: terraform -chdir=3-eks-deployment/terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=3-eks-deployment/terraform apply -auto-approve tfplan

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name eks-app-dev

      - name: Deploy to Kubernetes
        run: |
          # Replace variables in deployment manifest
          sed -i "s|\${DOCKERHUB_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g" 3-eks-deployment/k8s/deployment.yaml
          sed -i "s|\${GITHUB_SHA}|${{ github.sha }}|g" 3-eks-deployment/k8s/deployment.yaml
          
          # Apply the manifests
          kubectl apply -f 3-eks-deployment/k8s/
          
          # Wait for rollout to complete
          kubectl rollout status deployment/nodejs-express-app